### ISSUE TITLE
how do you inspect an Object?

### ISSUE THREAD

**Issue by afeld** [smtlaissezfaire/ndb#8]
Within the debugger, running `e myObject` outputs `#<Object>` - I saw some references in your code about how to inspect the contents (without full `verbose` mode), but it was unclear how to do so.  Would you mind adding the instruction?  Thanks!

**Comment by smtlaissezfaire** [comment]
Hey afeld,

That's a bit broken right now.

I haven't fixed it because the debugger built into node 0.4.x+ is basically the same thing (and is actively being improved + maintained by the core team).  It also doesn't have this bug ;)

I'll be putting up a notice in the README sometime this weekend.

Let me know if there is anything preventing you from using the builtin debugger.   I've already talked to ry and mentioned that I'd be happy to port any features in ndb to the built in debugger if they aren't already present.

**Comment by afeld** [comment]
Ha, had no idea that was available.  Thanks!
